# Generated by Django 5.2.7 on 2025-11-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="summary_snippet",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
