# Generated by Django 5.2.7 on 2025-11-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_article_summary_snippet_alter_user_first_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCreationLock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
    ]
