# Generated by Django 5.2.7 on 2025-12-29 00:20

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_article_content_trgm_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="article_title_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["summary_snippet"],
                name="article_summary_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
