# Generated by Django 5.2.7 on 2025-12-29 00:49

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


def populate_outgoing_links(apps, schema_editor):
    from main.models import Article

    for article in Article.objects.all():
        article.save()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_article_article_title_trgm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="outgoing_links",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(populate_outgoing_links, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="article",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["outgoing_links"], name="article_outgoing_links_gin"
            ),
        ),
    ]
